# Generated by Django 5.2.11 on 2026-05-08 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='found_skills',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='resume',
            name='improvements',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='resume',
            name='missing_skills',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='resume',
            name='recommendations',
            field=models.TextField(default=''),
        ),
    ]
