# Generated by Django 5.2.11 on 2026-05-18 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0003_resume_ai_feedback_resume_certifications_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='career',
            field=models.CharField(default='', max_length=200),
        ),
    ]
